export const REGISTER_FAIL      = 'REGISTER_FAIL'
export const REGISTER_SUCCESS   = 'REGISTER_SUCCESS'
export const LOGIN_FAIL         = 'LOGIN_FAIL'
export const LOGIN_SUCCESS      = 'LOGIN_SUCCESS'
export const AUTH_ERR           = 'AUTH_ERR'
export const LOGOUT_FAIL        = 'LOGOUT_FAIL'
export const LOGOUT_SUCCESS     = 'LOGOUT_SUCCESS'
export const USER_LOADING       = 'USER_LOADING'
export const USER_LOADED        = 'USER_LOADED'
export const GET_ERRORS         = 'GET_ERRORS'
export const CLEAR_ERRORS       = 'USER_LOADED'
export const CHANGE_PASSWORD_SUCCESS        = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL           = 'CHANGE_PASSWORD_FAIL'
export const UPDATING_PROFILE               = 'UPDATING_PROFILE'
export const UPDATED_PROFILE                = 'UPDATED_PROFILE'
export const UPLOAD_IMAGE_SUCCESS                = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAIL                   = 'UPLOAD_IMAGE_FAIL'
export const LOGIN_GOOGLE_FAIL                         = 'LOGIN_GOOGLE_FAIL'
export const LOGIN_GOOGLE_SUCCESS                      = 'LOGIN_GOOGLE_SUCCESS'
export const LOGIN_FACEBOOK_FAIL                       = 'LOGIN_FACEBOOK_FAIL'
export const LOGIN_FACEBOOK_SUCCESS                    = 'LOGIN_FACEBOOK_SUCCESS'

// caro
export const TOGGLE_PLAYER_IS_NEXT      = 'TOGGLE_PLAYER_IS_NEXT'
export const SETTING                    = 'SETTING'
export const CHANGE_STEP                = 'CHANGE_STEP'
export const CLICK_SQUARE               = 'CLICK_SQUARE'
export const SORT_MOVES                 = 'SORT_MOVES'
export const AUTO_CLICK_SQUARE          = 'AUTO_CLICK_SQUARE'
// export const TOGGLE_PLAYER_IS_NEXT      = 'TOGGLE_PLAYER_IS_NEXT'
// export const TOGGLE_PLAYER_IS_NEXT      = 'TOGGLE_PLAYER_IS_NEXT'

